version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/jessemichael.me
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" > ~/.npmrc
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # - run: npm test
      - run: npm run build
      - run: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
