/*
 * jessemichael.me internal
 *
 * Internal workings of Jesse Michael
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	fetcher "github.com/jesse0michael/jessemichael.me/internal/pkg/fetcher"
)

func main() {
	log.Printf("Server started")

	DefaultApiService := fetcher.NewDefaultApiService()
	DefaultApiController := fetcher.NewDefaultApiController(DefaultApiService)

	router := fetcher.NewRouter(DefaultApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
